# Generated by Django 4.1 on 2022-08-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_guides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_point', models.CharField(max_length=150, verbose_name='Город отправки')),
                ('arrival_point', models.CharField(max_length=150, verbose_name='Город прибытия')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('lenght', models.FloatField(verbose_name='Длина')),
                ('wight', models.FloatField(verbose_name='Ширина')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('declared_value_rate', models.IntegerField(verbose_name='Объявленная стоимость груза')),
                ('insurance_rate', models.IntegerField(verbose_name='Страховая стоимость груза')),
                ('is_test', models.BooleanField(default=False, verbose_name='Выключить тестовую версию')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_guides.deliverytype', verbose_name='Тип доставки')),
                ('type_of_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_guides.typeofcargo', verbose_name='Тип груза')),
                ('urgency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_guides.urgency', verbose_name='Срочность доставки')),
            ],
            options={
                'db_table': 'table_004_calc_parameters',
            },
        ),
    ]
